import { chromium } from 'playwright';
const browser = await chromium.launch({ channel: 'chrome' });
const page = await browser.newPage({ viewport: { width: 1600, height: 900 } });
const errors = [];
page.on('pageerror', (e) => errors.push(String(e)));
await page.goto('http://localhost:5199/', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(4000);
const modal = page.locator('.ls-overlay');
await modal.locator('button', { hasText: '1:37.007' }).click();
await page.waitForTimeout(1200);
await page.click('text=[change]');
await page.waitForTimeout(500);
await modal.locator('button', { hasText: 'Ghost' }).click();
await page.waitForTimeout(400);
await modal.locator('button', { hasText: '1:37.449' }).click();
await page.waitForTimeout(2500);
await page.screenshot({ path: '/tmp/f_chase.png', timeout: 90000 });
await page.keyboard.press('5');
await page.waitForTimeout(2500);
await page.screenshot({ path: '/tmp/f_tv.png', timeout: 90000 });
await page.keyboard.press('6');
await page.waitForTimeout(2000);
await page.screenshot({ path: '/tmp/f_cine1.png', timeout: 90000 });
await page.waitForTimeout(6000);
await page.screenshot({ path: '/tmp/f_cine2.png', timeout: 90000 });
const fps = await page.evaluate(() => new Promise((res) => {
  let n = 0; const s = performance.now();
  const tick = () => { n++; performance.now() - s < 2000 ? requestAnimationFrame(tick) : res((n / (performance.now() - s)) * 1000); };
  requestAnimationFrame(tick);
}));
console.log('FPS:', fps.toFixed(1), 'ERRORS:', JSON.stringify(errors));
await browser.close();
