#!/usr/bin/env python3
"""Flip the baked north->+z sign convention to north->-z in deployed track data.

Background
----------
src/replay/projection.ts's latLngToLocal() mapped north to +z. Combined with
east -> +x and up -> +y (three.js, right-handed), that is a parity flip: the
viewer rendered the entire world as a mirror image of reality (every real
right-hander appeared as a left-hander, and vice versa). The fix (north ->
-z) lives in projection.ts, but the *deployed* public/data/tracks/*/track.json
and features.json files were generated by the Python pipeline using the same
wrong convention, so their baked x/z coordinates are mirrored too and must be
migrated to match.

This script is deterministic and does not touch the network or re-fetch
anything from OSM (OSM geometry may have drifted since these files were
generated; we need to flip exactly what is already deployed, bit for bit
otherwise). It only negates the z coordinates that were derived from
latitude, on the two files per track:

  track.json:
    - centerline[i].z is negated for every point.
    - bounds.z: [min, max] becomes [-max, -min] (kept sorted).
    - Nothing else changes: x, y, lat, lng, dist, alt, sectors, origin.

  features.json:
    - outline[i][1] (z) is negated for every vertex of every feature.
    - Nothing else changes: outline[i][0] (x), origin, feature count/order.

Idempotency
-----------
Each file gets a top-level "zConvention": "north-negative-z" marker once
migrated; a file that already carries this marker is left untouched (skipped)
so re-running this script is a safe no-op.

Backups
-------
Before writing, each file is copied to "<name>.bak-mirror" (skipped if that
backup already exists, so a second run never clobbers the pre-migration
snapshot).

Usage
-----
    python3 pipeline/migrate_flip_z.py
"""

from __future__ import annotations

import json
from pathlib import Path

V2_ROOT = Path(__file__).resolve().parents[1]
TRACKS_DIR = V2_ROOT / "public" / "data" / "tracks"
TRACK_IDS = ("barber", "fuji")
MARKER_KEY = "zConvention"
MARKER_VALUE = "north-negative-z"


def neg(value: float) -> float:
    """Negate, normalising -0.0 to 0.0 for tidy JSON output."""
    result = -value
    return 0.0 if result == 0 else result


def backup(path: Path) -> bool:
    """Copy path to <name>.bak-mirror unless that backup already exists.

    Returns True if a fresh backup was written, False if one already existed
    (left untouched, per the "never overwrite existing backups" rule).
    """
    bak = path.with_name(path.name + ".bak-mirror")
    if bak.exists():
        print(f"    (backup already exists, leaving as-is: {bak.name})")
        return False
    bak.write_bytes(path.read_bytes())
    print(f"    backed up -> {bak.name}")
    return True


def migrate_track_json(track_id: str) -> None:
    path = TRACKS_DIR / track_id / "track.json"
    if not path.exists():
        print(f"  track.json: not found, skipping")
        return

    data = json.loads(path.read_text())
    if data.get(MARKER_KEY) == MARKER_VALUE:
        print(f"  track.json: already migrated ({MARKER_KEY}={MARKER_VALUE!r}), skipping")
        return

    backup(path)

    centerline = data["centerline"]
    point_count = len(centerline)
    z_before = [p["z"] for p in centerline]

    for point in centerline:
        point["z"] = neg(point["z"])

    old_bounds_z = list(data["bounds"]["z"])
    new_bounds_z = [neg(old_bounds_z[1]), neg(old_bounds_z[0])]
    data["bounds"]["z"] = new_bounds_z

    data[MARKER_KEY] = MARKER_VALUE

    path.write_text(json.dumps(data, indent=2) + "\n")

    z_after = [p["z"] for p in centerline]
    print(f"  track.json: {point_count} centerline points (count unchanged)")
    print(f"    z range before: [{min(z_before):.3f}, {max(z_before):.3f}]")
    print(f"    z range after:  [{min(z_after):.3f}, {max(z_after):.3f}]")
    print(f"    bounds.z before: {old_bounds_z} -> after: {new_bounds_z}")

    # Sanity: negating is its own inverse and shouldn't change point count or
    # the (unordered) set of |z| magnitudes.
    assert len(centerline) == point_count
    mags_before = sorted(round(abs(v), 6) for v in z_before)
    mags_after = sorted(round(abs(v), 6) for v in z_after)
    assert mags_before == mags_after, "z magnitudes changed — this should be a pure sign flip"


def migrate_features_json(track_id: str) -> None:
    path = TRACKS_DIR / track_id / "features.json"
    if not path.exists():
        print(f"  features.json: not found, skipping")
        return

    data = json.loads(path.read_text())
    if data.get(MARKER_KEY) == MARKER_VALUE:
        print(f"  features.json: already migrated ({MARKER_KEY}={MARKER_VALUE!r}), skipping")
        return

    backup(path)

    features = data["features"]
    feature_count = len(features)
    vertex_count_before = 0
    z_before_min, z_before_max = float("inf"), float("-inf")

    for feature in features:
        new_outline = []
        for x, z in feature["outline"]:
            vertex_count_before += 1
            z_before_min = min(z_before_min, z)
            z_before_max = max(z_before_max, z)
            new_outline.append([x, neg(z)])
        feature["outline"] = new_outline

    data[MARKER_KEY] = MARKER_VALUE

    path.write_text(json.dumps(data, separators=(",", ":")) + "\n")

    vertex_count_after = sum(len(f["outline"]) for f in features)
    z_after_min = min(v[1] for f in features for v in f["outline"])
    z_after_max = max(v[1] for f in features for v in f["outline"])

    print(f"  features.json: {feature_count} features, {vertex_count_before} outline vertices (counts unchanged)")
    print(f"    z range before: [{z_before_min:.2f}, {z_before_max:.2f}]")
    print(f"    z range after:  [{z_after_min:.2f}, {z_after_max:.2f}]")

    assert vertex_count_after == vertex_count_before
    assert len(features) == feature_count


def main() -> int:
    for track_id in TRACK_IDS:
        print(f"=== {track_id} ===")
        migrate_track_json(track_id)
        migrate_features_json(track_id)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
